# Generated by Django 6.1.1 on 2026-09-14 03:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Entry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("placeName", models.CharField(max_length=200)),
                ("location", models.CharField(max_length=200)),
                ("timeWeWent", models.DateTimeField()),
                (
                    "foodScore",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ]
                    ),
                ),
                (
                    "priceScore",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ]
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("photo", models.BinaryField(blank=True, null=True)),
                ("photoType", models.CharField(blank=True, max_length=100, null=True)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
